services:
  - type: web
    name: ai-asset-finder-backend
    env: docker
    rootDir: backend
    region: ohio
    plan: starter
    healthCheckPath: /
    envVars:
      - key: GROQ_API_KEY
        sync: false
